;;; org-zk.el --- A lightweight org-mode Zettelkasten -*- lexical-binding: t; -*-

;; Author: bucksbunni
;; Version: 0.1.0
;; Keywords: outlines, notes, zettelkasten
;; Package-Requires: ((emacs "27.1") (org "9.5"))
;; URL: https://github.com/bucksbunni/org-zk

;;; Commentary:

;; A minimal Zettelkasten built on top of org-mode and Doom's bundled
;; completion stack (Vertico + Consult + ripgrep).
;;
;; Conventions:
;;   - Each note ("zettel") is a single .org file.
;;   - Every zettel has a UID generated by org's own `org-id-new',
;;     so the format is controlled by `org-id-method' (and, for the
;;     timestamp method, `org-id-ts-format'). To get YYMMDDHHMMSS ids:
;;
;;       (setq org-id-method 'ts
;;             org-id-ts-format "%y%m%d%H%M%S")
;;
;;   - Filenames follow the pattern "Title (UID).org".
;;   - The same UID is stored in the file's :ID: property, so org's
;;     native id: links resolve automatically via `org-id'.
;;   - Tags live on a `#+filetags:' line in the `:tag1:tag2:' format.
;;
;; All public commands are prefixed `zk/'; internal helpers use `org-zk--'.

;;; Code:

(require 'org)
(require 'org-id)
(require 'seq)

;;;; Customization

(defgroup org-zk nil
  "A lightweight org-mode Zettelkasten."
  :group 'org
  :prefix "org-zk-")

(defcustom org-zk-directory "~/zettelkasten/"
  "Default directory in which zettels are stored.
If nil, commands fall back to the current project root, then to
the current buffer's directory."
  :type '(choice (directory :tag "Fixed directory")
                 (const :tag "Use project root" nil))
  :group 'org-zk)

;;;; Internal helpers

(defun org-zk--base-directory ()
  "Resolve the directory in which to create or search zettels.
Prefers `org-zk-directory'; falls back to the project root, then to
`default-directory'."
  (or org-zk-directory
      (and (fboundp 'doom-project-root) (doom-project-root))
      default-directory))

(defun org-zk--uid ()
  "Generate a UID using org's own `org-id-new'.
The format is therefore governed by `org-id-method' (e.g. `ts'
for timestamps, `uuid' for UUIDs) and, for the timestamp method,
`org-id-ts-format'."
  (org-id-new))

(defun org-zk--path (title uid)
  "Build the absolute path for a zettel named TITLE with UID."
  (expand-file-name (format "%s (%s).org" title uid)
                    (org-zk--base-directory)))

(defun org-zk--ensure-directory ()
  "Create the zettel base directory if it does not yet exist."
  (let ((dir (org-zk--base-directory)))
    (unless (file-directory-p dir)
      (make-directory dir t))))

(defun org-zk--create (title &optional content)
  "Create a zettel file titled TITLE with optional CONTENT.
Writes the org front matter (title + :ID: property) and saves the
file. Returns a cons cell (UID . PATH)."
  (org-zk--ensure-directory)
  (let* ((uid (org-zk--uid))
         (path (org-zk--path title uid)))
    (with-current-buffer (find-file-noselect path)
      (insert (format "#+title: %s\n:PROPERTIES:\n:ID: %s\n:END:\n\n%s"
                       title uid (or content "")))
      (save-buffer))
    (cons uid path)))

(defun org-zk--insert-link (uid title)
  "Insert a native org id: link to UID with description TITLE at point."
  (insert (format "[[id:%s][%s]]" uid title)))

(defun org-zk--files ()
  "Return a list of all zettel .org files in the base directory."
  (directory-files (org-zk--base-directory) t "\\.org\\'"))

(defun org-zk--collect-tags ()
  "Scan all zettels and return a de-duplicated list of their tags.
Only the first 2000 bytes of each file are read for speed."
  (let (tags)
    (dolist (file (org-zk--files))
      (with-temp-buffer
        (insert-file-contents file nil 0 2000)
        (goto-char (point-min))
        (when (re-search-forward "^#\\+filetags:\\s-*:\\(.*\\):" nil t)
          (dolist (tag (split-string (match-string 1) ":" t))
            (push tag tags)))))
    (delete-dups tags)))

;;;; Commands: creating zettels

;;;###autoload
(defun zk/new (title)
  "Create a new zettel titled TITLE and visit it."
  (interactive "sTitle: ")
  (find-file (cdr (org-zk--create title))))

;;;###autoload
(defun zk/new-from-region ()
  "Extract the active region into a new zettel.
Prompts for a title, moves the selected text into the new note,
and replaces the original selection with a link to it. This is
the classic \"promote a thought to its own note\" operation."
  (interactive)
  (unless (use-region-p)
    (user-error "No active region"))
  (let* ((content (buffer-substring-no-properties (region-beginning) (region-end)))
         (title (read-string "Title: "))
         (result (org-zk--create title content))
         (uid (car result)))
    (delete-region (region-beginning) (region-end))
    (org-zk--insert-link uid title)))

;;;###autoload
(defun zk/new-with-link (title &optional visit)
  "Create a new zettel titled TITLE and insert a link at point.
With a prefix argument (VISIT non-nil), also open the new note."
  (interactive (list (read-string "Title: ") current-prefix-arg))
  (let* ((result (org-zk--create title))
         (uid (car result))
         (path (cdr result)))
    (org-zk--insert-link uid title)
    (when visit (find-file path))))

;;;; Commands: tagging

;;;###autoload
(defun zk/add-tag ()
  "Add a tag to the current zettel's `#+filetags:' line.
Offers completion over tags already used elsewhere. Creates the
filetags line just after the title if it does not yet exist."
  (interactive)
  (let ((tag (completing-read "Tag: " (org-zk--collect-tags))))
    (save-excursion
      (goto-char (point-min))
      (if (re-search-forward "^#\\+filetags:\\s-*:\\(.*\\):" nil t)
          ;; Existing filetags line: append unless already present.
          (let ((current (split-string (match-string 1) ":" t)))
            (unless (member tag current)
              (push tag current))
            (replace-match (format "#+filetags: :%s:"
                                    (mapconcat #'identity current ":"))))
        ;; No filetags line yet: insert one right after the title.
        (goto-char (point-min))
        (re-search-forward "^#\\+title:.*$")
        (end-of-line)
        (insert (format "\n#+filetags: :%s:" tag))))
    (save-buffer)))

;;;###autoload
(defun zk/find-by-tag ()
  "Find and open a zettel filtered by a chosen tag."
  (interactive)
  (let* ((tag (completing-read "Tag: " (org-zk--collect-tags)))
         (matches
          (seq-filter
           (lambda (file)
             (with-temp-buffer
               (insert-file-contents file nil 0 2000)
               (goto-char (point-min))
               (and (re-search-forward "^#\\+filetags:.*$" nil t)
                    (string-match-p (format ":%s:" (regexp-quote tag))
                                    (match-string 0)))))
           (org-zk--files))))
    (if matches
        (find-file (completing-read "Zettel: " matches))
      (message "No zettels tagged :%s:" tag))))

;;;; Commands: finding & searching

;;;###autoload
(defun zk/find-file ()
  "Fuzzy find a zettel by filename/title via `consult-find'."
  (interactive)
  (let ((default-directory (org-zk--base-directory)))
    (consult-find)))

;;;###autoload
(defun zk/search ()
  "Fuzzy search across zettel content via `consult-ripgrep'."
  (interactive)
  (consult-ripgrep (org-zk--base-directory)))

;;;; Commands: following & previewing links

;;;###autoload
(defun zk/follow-link-at-point ()
  "Follow the org link at point.
Thin wrapper around `org-open-at-point' for a consistent `zk/'
entry point; native id: links resolve automatically via org-id."
  (interactive)
  (org-open-at-point))

;;;###autoload
(defun zk/preview-link-at-point ()
  "Preview the zettel linked at point in a window below.
Keeps focus in the current window so you can glance at the target
without losing your place. Only handles id: links."
  (interactive)
  (let* ((context (org-element-context))
         (type (org-element-property :type context))
         (path (org-element-property :path context)))
    (if (and path (eq type 'id))
        (let ((marker (org-id-find path 'marker)))
          (if marker
              (save-selected-window
                (pop-to-buffer (marker-buffer marker)
                                '((display-buffer-below-selected)
                                  (window-height . 0.4)))
                (goto-char marker)
                (recenter 0))
            (message "Zettel not found: %s" path)))
      (message "No id: link at point"))))

;;;; Keybindings (Doom)

;; Wrapped in `with-eval-after-load' so this file can be loaded safely
;; even outside Doom; the `map!' macro only exists once Doom is up.
(with-eval-after-load 'doom-keybinds
  (when (fboundp 'map!)
    (map! :leader
          (:prefix ("n z" . "zk")
           :desc "New zettel"      "n" #'zk/new
           :desc "New from region" "r" #'zk/new-from-region
           :desc "New with link"   "l" #'zk/new-with-link
           :desc "Add tag"         "t" #'zk/add-tag
           :desc "Find by tag"     "T" #'zk/find-by-tag
           :desc "Find file"       "f" #'zk/find-file
           :desc "Search content"  "s" #'zk/search
           :desc "Follow link"     "o" #'zk/follow-link-at-point
           :desc "Preview link"    "p" #'zk/preview-link-at-point))))

(provide 'org-zk)

;;; org-zk.el ends here
