;;; org-zk.el --- A lightweight org-mode Zettelkasten -*- lexical-binding: t; -*-

;; Author: bucksbunni
;; Version: 0.1.0
;; Keywords: outlines, notes, zettelkasten
;; Package-Requires: ((emacs "27.1") (org "9.5"))
;; URL: https://github.com/bucksbunni/org-zk

;;; Commentary:

;; A minimal Zettelkasten built on top of org-mode and Doom's bundled
;; completion stack (Vertico + Consult + ripgrep).
;;
;; Conventions:
;;   - Each note ("zettel") is a single .org file.
;;   - Every zettel has a UID generated by org's own `org-id-new',
;;     so the format is controlled by `org-id-method' (and, for the
;;     timestamp method, `org-id-ts-format'). To get YYMMDDHHMMSS ids:
;;
;;       (setq org-id-method 'ts
;;             org-id-ts-format "%y%m%d%H%M%S")
;;
;;   - Filenames follow `org-zk-filename-style': by default "slug_uid.org"
;;     (a lowercased, underscore-separated title); set it to `title' for
;;     the classic "Title (uid).org" form.
;;   - The same UID is stored in the file's :ID: property and registered
;;     with org-id at creation time, so native id: links resolve
;;     immediately via `org-id'. If you ever see "Cannot find entry
;;     with ID" for an older zettel, run `org-zk/rebuild-id-locations'.
;;   - Tags live on a `#+filetags:' line in the `:tag1:tag2:' format.
;;   - Links can be inserted bare (`[[id:UID]]') or with the target's
;;     title as the description (`[[id:UID][Title]]'); each form has its
;;     own command for both new and existing zettels.
;;
;; All public commands are prefixed `org-zk/'; internal helpers use `org-zk--'.

;;; Code:

(require 'org)
(require 'org-id)
(require 'seq)

;;;; Customization

(defgroup org-zk nil
  "A lightweight org-mode Zettelkasten."
  :group 'org
  :prefix "org-zk-")

(defcustom org-zk-directory "~/zettelkasten/"
  "Default directory in which zettels are stored.
If nil, commands fall back to the current project root, then to
the current buffer's directory."
  :type '(choice (directory :tag "Fixed directory")
                 (const :tag "Use project root" nil))
  :group 'org-zk)

(defcustom org-zk-filename-style 'slug
  "Template controlling how zettel filenames are built.
`slug' yields \"slug_uid.org\", where the slug is the title
lowercased with runs of non-alphanumerics collapsed to single
underscores. `title' yields the classic \"Title (uid).org\"."
  :type '(choice (const :tag "slug_uid.org" slug)
                 (const :tag "Title (uid).org" title))
  :group 'org-zk)

;;;; Internal helpers

(defun org-zk--base-directory ()
  "Resolve the directory in which to create or search zettels.
Prefers `org-zk-directory'; falls back to the project root, then to
`default-directory'."
  (or org-zk-directory
      (and (fboundp 'doom-project-root) (doom-project-root))
      default-directory))

(defun org-zk--uid ()
  "Generate a UID using org's own `org-id-new'.
The format is therefore governed by `org-id-method' (e.g. `ts'
for timestamps, `uuid' for UUIDs) and, for the timestamp method,
`org-id-ts-format'."
  (org-id-new))

(defun org-zk--slug (title)
  "Convert TITLE into a lowercase, underscore-separated slug.
Runs of non-alphanumeric characters become a single underscore,
and leading/trailing underscores are stripped."
  (let ((s (replace-regexp-in-string "[^a-z0-9]+" "_" (downcase title))))
    (replace-regexp-in-string "\\`_+\\|_+\\'" "" s)))

(defun org-zk--filename (title uid)
  "Build the bare zettel filename for TITLE and UID.
Honors `org-zk-filename-style'."
  (pcase org-zk-filename-style
    ('slug (format "%s_%s.org" (org-zk--slug title) uid))
    (_     (format "%s (%s).org" title uid))))

(defun org-zk--path (title uid)
  "Build the absolute path for a zettel named TITLE with UID."
  (expand-file-name (org-zk--filename title uid)
                    (org-zk--base-directory)))

(defun org-zk--ensure-directory ()
  "Create the zettel base directory if it does not yet exist."
  (let ((dir (org-zk--base-directory)))
    (unless (file-directory-p dir)
      (make-directory dir t))))

(defun org-zk--create (title &optional content)
  "Create a zettel file titled TITLE with optional CONTENT.
Writes the org front matter (:ID: property + title), saves the
file, and registers UID with org-id so id: links to it resolve
immediately. The :PROPERTIES: drawer must come before #+title:
-- org only recognizes a file-level property drawer as such when
it is the very first thing in the buffer; otherwise :ID: is
parsed as plain text and never resolves. Returns a cons cell
(UID . PATH)."
  (org-zk--ensure-directory)
  (let* ((uid (org-zk--uid))
         (path (org-zk--path title uid)))
    (with-current-buffer (find-file-noselect path)
      (insert (format ":PROPERTIES:\n:ID: %s\n:END:\n#+title: %s\n\n%s"
                       uid title (or content "")))
      (save-buffer))
    (org-id-add-location uid path)
    (cons uid path)))

(defun org-zk--insert-link (uid &optional description)
  "Insert a native org id: link to UID at point.
With DESCRIPTION non-nil, use it as the link's visible text
\(`[[id:UID][DESCRIPTION]]'); otherwise insert a bare
`[[id:UID]]' link."
  (insert (if (and description (not (string-empty-p description)))
              (format "[[id:%s][%s]]" uid description)
            (format "[[id:%s]]" uid))))

(defun org-zk--files ()
  "Return a list of all zettel .org files in the base directory."
  (directory-files (org-zk--base-directory) t "\\.org\\'"))

(defun org-zk--file-field (file regexp)
  "Return the first capture group of REGEXP in FILE, or nil.
Only the first 2000 bytes of FILE are scanned, for speed."
  (with-temp-buffer
    (insert-file-contents file nil 0 2000)
    (goto-char (point-min))
    (when (re-search-forward regexp nil t)
      (match-string 1))))

(defun org-zk--file-title (file)
  "Return the `#+title:' of FILE, falling back to its base name."
  (or (org-zk--file-field file "^#\\+title:\\s-*\\(.*\\)$")
      (file-name-base file)))

(defun org-zk--file-id (file)
  "Return the `:ID:' property of FILE, or nil."
  (org-zk--file-field file "^\\s-*:ID:\\s-*\\(\\S-+\\)"))

(defun org-zk--read-zettel (prompt)
  "Prompt with PROMPT to pick an existing zettel via completion.
Returns a cons cell (UID . TITLE) for the chosen note."
  (let* ((table (mapcar (lambda (file)
                          (cons (org-zk--file-title file)
                                (org-zk--file-id file)))
                        (org-zk--files)))
         (title (completing-read prompt table nil t))
         (uid (cdr (assoc title table))))
    (cons uid title)))

(defun org-zk--collect-tags ()
  "Scan all zettels and return a de-duplicated list of their tags.
Only the first 2000 bytes of each file are read for speed."
  (let (tags)
    (dolist (file (org-zk--files))
      (with-temp-buffer
        (insert-file-contents file nil 0 2000)
        (goto-char (point-min))
        (when (re-search-forward "^#\\+filetags:\\s-*:\\(.*\\):" nil t)
          (dolist (tag (split-string (match-string 1) ":" t))
            (push tag tags)))))
    (delete-dups tags)))

;;;; Commands: creating zettels

;;;###autoload
(defun org-zk/new (title)
  "Create a new zettel titled TITLE and visit it."
  (interactive "sTitle: ")
  (find-file (cdr (org-zk--create title))))

;;;###autoload
(defun org-zk/new-from-region ()
  "Extract the active region into a new zettel.
Prompts for a title, moves the selected text into the new note,
and replaces the original selection with a link to it. This is
the classic \"promote a thought to its own note\" operation."
  (interactive)
  (unless (use-region-p)
    (user-error "No active region"))
  (let* ((content (buffer-substring-no-properties (region-beginning) (region-end)))
         (title (read-string "Title: "))
         (result (org-zk--create title content))
         (uid (car result)))
    (delete-region (region-beginning) (region-end))
    (org-zk--insert-link uid)))

;;;###autoload
(defun org-zk/new-with-link (title &optional visit)
  "Create a new zettel titled TITLE and insert a bare link at point.
With a prefix argument (VISIT non-nil), also open the new note."
  (interactive (list (read-string "Title: ") current-prefix-arg))
  (let* ((result (org-zk--create title))
         (uid (car result))
         (path (cdr result)))
    (org-zk--insert-link uid)
    (when visit (find-file path))))

;;;###autoload
(defun org-zk/new-with-titled-link (title &optional visit)
  "Create a new zettel titled TITLE and insert a titled link at point.
The link shows TITLE as its description (`[[id:UID][TITLE]]').
With a prefix argument (VISIT non-nil), also open the new note."
  (interactive (list (read-string "Title: ") current-prefix-arg))
  (let* ((result (org-zk--create title))
         (uid (car result))
         (path (cdr result)))
    (org-zk--insert-link uid title)
    (when visit (find-file path))))

;;;; Commands: linking to existing zettels

;;;###autoload
(defun org-zk/insert-link ()
  "Pick an existing zettel and insert a bare link to it at point."
  (interactive)
  (org-zk--insert-link (car (org-zk--read-zettel "Link to zettel: "))))

;;;###autoload
(defun org-zk/insert-link-titled ()
  "Pick an existing zettel and insert a titled link to it at point.
The link shows the target's title as its description."
  (interactive)
  (pcase-let ((`(,uid . ,title) (org-zk--read-zettel "Link to zettel: ")))
    (org-zk--insert-link uid title)))

;;;; Commands: tagging

;;;###autoload
(defun org-zk/add-tag ()
  "Add a tag to the current zettel's `#+filetags:' line.
Offers completion over tags already used elsewhere. Creates the
filetags line just after the title if it does not yet exist."
  (interactive)
  (let ((tag (completing-read "Tag: " (org-zk--collect-tags))))
    (save-excursion
      (goto-char (point-min))
      (if (re-search-forward "^#\\+filetags:\\s-*:\\(.*\\):" nil t)
          ;; Existing filetags line: append unless already present.
          (let ((current (split-string (match-string 1) ":" t)))
            (unless (member tag current)
              (push tag current))
            (replace-match (format "#+filetags: :%s:"
                                    (mapconcat #'identity current ":"))))
        ;; No filetags line yet: insert one right after the title.
        (goto-char (point-min))
        (re-search-forward "^#\\+title:.*$")
        (end-of-line)
        (insert (format "\n#+filetags: :%s:" tag))))
    (save-buffer)))

;;;###autoload
(defun org-zk/find-by-tag ()
  "Find and open a zettel filtered by a chosen tag."
  (interactive)
  (let* ((tag (completing-read "Tag: " (org-zk--collect-tags)))
         (matches
          (seq-filter
           (lambda (file)
             (with-temp-buffer
               (insert-file-contents file nil 0 2000)
               (goto-char (point-min))
               (and (re-search-forward "^#\\+filetags:.*$" nil t)
                    (string-match-p (format ":%s:" (regexp-quote tag))
                                    (match-string 0)))))
           (org-zk--files))))
    (if matches
        (find-file (completing-read "Zettel: " matches))
      (message "No zettels tagged :%s:" tag))))

;;;###autoload
(defun org-zk/rebuild-id-locations ()
  "Re-scan all zettels and register their UIDs with org-id.
Run this if id: links report \"Cannot find entry with ID\" --
typically for zettels created before `org-zk--create' started
registering locations itself, or after `org-id-locations-file'
was deleted or got out of sync."
  (interactive)
  (org-id-update-id-locations (org-zk--files))
  (message "org-zk: id locations rebuilt"))

;;;; Commands: finding & searching

;;;###autoload
(defun org-zk/find-file ()
  "Fuzzy find a zettel by filename/title via `consult-find'."
  (interactive)
  (let ((default-directory (org-zk--base-directory)))
    (consult-find)))

;;;###autoload
(defun org-zk/search ()
  "Fuzzy search across zettel content via `consult-ripgrep'."
  (interactive)
  (consult-ripgrep (org-zk--base-directory)))

;;;; Commands: following & previewing links

;;;###autoload
(defun org-zk/follow-link-at-point ()
  "Follow the org link at point.
Thin wrapper around `org-open-at-point' for a consistent `org-zk/'
entry point; native id: links resolve automatically via org-id."
  (interactive)
  (org-open-at-point))

;;;###autoload
(defun org-zk/preview-link-at-point ()
  "Preview the zettel linked at point in a window below.
Keeps focus in the current window so you can glance at the target
without losing your place. Only handles id: links."
  (interactive)
  (let* ((context (org-element-context))
         (type (org-element-property :type context))
         (path (org-element-property :path context)))
    (if (and path (eq type 'id))
        (let ((marker (org-id-find path 'marker)))
          (if marker
              (save-selected-window
                (pop-to-buffer (marker-buffer marker)
                                '((display-buffer-below-selected)
                                  (window-height . 0.4)))
                (goto-char marker)
                (recenter 0))
            (message "Zettel not found: %s" path)))
      (message "No id: link at point"))))

;;;; Keybindings (Doom)

;; Wrapped in `with-eval-after-load' so this file can be loaded safely
;; even outside Doom; the `map!' macro only exists once Doom is up.
(with-eval-after-load 'doom-keybinds
  (when (fboundp 'map!)
    (map! :leader
          (:prefix ("n z" . "org-zk")
           :desc "New zettel"      "n" #'org-zk/new
           :desc "New from region" "r" #'org-zk/new-from-region
           :desc "New with link"   "l" #'org-zk/new-with-link
           :desc "New with titled link" "L" #'org-zk/new-with-titled-link
           :desc "Insert link"     "i" #'org-zk/insert-link
           :desc "Insert titled link" "I" #'org-zk/insert-link-titled
           :desc "Add tag"         "t" #'org-zk/add-tag
           :desc "Find by tag"     "T" #'org-zk/find-by-tag
           :desc "Find file"       "f" #'org-zk/find-file
           :desc "Search content"  "s" #'org-zk/search
           :desc "Follow link"     "o" #'org-zk/follow-link-at-point
           :desc "Preview link"    "p" #'org-zk/preview-link-at-point
           :desc "Rebuild ID locations" "R" #'org-zk/rebuild-id-locations))))

(provide 'org-zk)

;;; org-zk.el ends here
